server:
  port: 7900

spring:
  application:
    name: eureka-server

logging:
  level:
    root: INFO
    com.multiple.eureka: DEBUG

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7900/eureka
#      defaultZone: http://user:123456@localhost:7900/eureka




